/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated.teacher.index'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated.student.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedTeacherUploadsRouteImport } from './routes/_authenticated.teacher.uploads'
import { Route as AuthenticatedTeacherStudentsRouteImport } from './routes/_authenticated.teacher.students'
import { Route as AuthenticatedTeacherSessionsRouteImport } from './routes/_authenticated.teacher.sessions'
import { Route as AuthenticatedTeacherScheduleRouteImport } from './routes/_authenticated.teacher.schedule'
import { Route as AuthenticatedTeacherQuestionGenerationRouteImport } from './routes/_authenticated.teacher.question-generation'
import { Route as AuthenticatedTeacherLeavesRouteImport } from './routes/_authenticated.teacher.leaves'
import { Route as AuthenticatedTeacherExamsRouteImport } from './routes/_authenticated.teacher.exams'
import { Route as AuthenticatedTeacherDoubtsRouteImport } from './routes/_authenticated.teacher.doubts'
import { Route as AuthenticatedStudentProgressRouteImport } from './routes/_authenticated.student.progress'
import { Route as AuthenticatedStudentMaterialsRouteImport } from './routes/_authenticated.student.materials'
import { Route as AuthenticatedStudentLecturesRouteImport } from './routes/_authenticated.student.lectures'
import { Route as AuthenticatedStudentAssessmentsRouteImport } from './routes/_authenticated.student.assessments'
import { Route as AuthenticatedStudentAskDoubtRouteImport } from './routes/_authenticated.student.ask-doubt'
import { Route as AuthenticatedStudentAiHubRouteImport } from './routes/_authenticated.student.ai-hub'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated.admin.teachers'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated.admin.students'
import { Route as AuthenticatedAdminLeavesRouteImport } from './routes/_authenticated.admin.leaves'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated.admin.access'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherUploadsRoute =
  AuthenticatedTeacherUploadsRouteImport.update({
    id: '/teacher/uploads',
    path: '/teacher/uploads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherStudentsRoute =
  AuthenticatedTeacherStudentsRouteImport.update({
    id: '/teacher/students',
    path: '/teacher/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherSessionsRoute =
  AuthenticatedTeacherSessionsRouteImport.update({
    id: '/teacher/sessions',
    path: '/teacher/sessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherScheduleRoute =
  AuthenticatedTeacherScheduleRouteImport.update({
    id: '/teacher/schedule',
    path: '/teacher/schedule',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherQuestionGenerationRoute =
  AuthenticatedTeacherQuestionGenerationRouteImport.update({
    id: '/teacher/question-generation',
    path: '/teacher/question-generation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherLeavesRoute =
  AuthenticatedTeacherLeavesRouteImport.update({
    id: '/teacher/leaves',
    path: '/teacher/leaves',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherExamsRoute =
  AuthenticatedTeacherExamsRouteImport.update({
    id: '/teacher/exams',
    path: '/teacher/exams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherDoubtsRoute =
  AuthenticatedTeacherDoubtsRouteImport.update({
    id: '/teacher/doubts',
    path: '/teacher/doubts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentProgressRoute =
  AuthenticatedStudentProgressRouteImport.update({
    id: '/student/progress',
    path: '/student/progress',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentMaterialsRoute =
  AuthenticatedStudentMaterialsRouteImport.update({
    id: '/student/materials',
    path: '/student/materials',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentLecturesRoute =
  AuthenticatedStudentLecturesRouteImport.update({
    id: '/student/lectures',
    path: '/student/lectures',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentAssessmentsRoute =
  AuthenticatedStudentAssessmentsRouteImport.update({
    id: '/student/assessments',
    path: '/student/assessments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentAskDoubtRoute =
  AuthenticatedStudentAskDoubtRouteImport.update({
    id: '/student/ask-doubt',
    path: '/student/ask-doubt',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentAiHubRoute =
  AuthenticatedStudentAiHubRouteImport.update({
    id: '/student/ai-hub',
    path: '/student/ai-hub',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/admin/teachers',
    path: '/admin/teachers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLeavesRoute =
  AuthenticatedAdminLeavesRouteImport.update({
    id: '/admin/leaves',
    path: '/admin/leaves',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/admin/access',
    path: '/admin/access',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/leaves': typeof AuthenticatedAdminLeavesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/student/ai-hub': typeof AuthenticatedStudentAiHubRoute
  '/student/ask-doubt': typeof AuthenticatedStudentAskDoubtRoute
  '/student/assessments': typeof AuthenticatedStudentAssessmentsRoute
  '/student/lectures': typeof AuthenticatedStudentLecturesRoute
  '/student/materials': typeof AuthenticatedStudentMaterialsRoute
  '/student/progress': typeof AuthenticatedStudentProgressRoute
  '/teacher/doubts': typeof AuthenticatedTeacherDoubtsRoute
  '/teacher/exams': typeof AuthenticatedTeacherExamsRoute
  '/teacher/leaves': typeof AuthenticatedTeacherLeavesRoute
  '/teacher/question-generation': typeof AuthenticatedTeacherQuestionGenerationRoute
  '/teacher/schedule': typeof AuthenticatedTeacherScheduleRoute
  '/teacher/sessions': typeof AuthenticatedTeacherSessionsRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsRoute
  '/teacher/uploads': typeof AuthenticatedTeacherUploadsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/leaves': typeof AuthenticatedAdminLeavesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/student/ai-hub': typeof AuthenticatedStudentAiHubRoute
  '/student/ask-doubt': typeof AuthenticatedStudentAskDoubtRoute
  '/student/assessments': typeof AuthenticatedStudentAssessmentsRoute
  '/student/lectures': typeof AuthenticatedStudentLecturesRoute
  '/student/materials': typeof AuthenticatedStudentMaterialsRoute
  '/student/progress': typeof AuthenticatedStudentProgressRoute
  '/teacher/doubts': typeof AuthenticatedTeacherDoubtsRoute
  '/teacher/exams': typeof AuthenticatedTeacherExamsRoute
  '/teacher/leaves': typeof AuthenticatedTeacherLeavesRoute
  '/teacher/question-generation': typeof AuthenticatedTeacherQuestionGenerationRoute
  '/teacher/schedule': typeof AuthenticatedTeacherScheduleRoute
  '/teacher/sessions': typeof AuthenticatedTeacherSessionsRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsRoute
  '/teacher/uploads': typeof AuthenticatedTeacherUploadsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/leaves': typeof AuthenticatedAdminLeavesRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/student/ai-hub': typeof AuthenticatedStudentAiHubRoute
  '/_authenticated/student/ask-doubt': typeof AuthenticatedStudentAskDoubtRoute
  '/_authenticated/student/assessments': typeof AuthenticatedStudentAssessmentsRoute
  '/_authenticated/student/lectures': typeof AuthenticatedStudentLecturesRoute
  '/_authenticated/student/materials': typeof AuthenticatedStudentMaterialsRoute
  '/_authenticated/student/progress': typeof AuthenticatedStudentProgressRoute
  '/_authenticated/teacher/doubts': typeof AuthenticatedTeacherDoubtsRoute
  '/_authenticated/teacher/exams': typeof AuthenticatedTeacherExamsRoute
  '/_authenticated/teacher/leaves': typeof AuthenticatedTeacherLeavesRoute
  '/_authenticated/teacher/question-generation': typeof AuthenticatedTeacherQuestionGenerationRoute
  '/_authenticated/teacher/schedule': typeof AuthenticatedTeacherScheduleRoute
  '/_authenticated/teacher/sessions': typeof AuthenticatedTeacherSessionsRoute
  '/_authenticated/teacher/students': typeof AuthenticatedTeacherStudentsRoute
  '/_authenticated/teacher/uploads': typeof AuthenticatedTeacherUploadsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/admin/access'
    | '/admin/leaves'
    | '/admin/students'
    | '/admin/teachers'
    | '/student/ai-hub'
    | '/student/ask-doubt'
    | '/student/assessments'
    | '/student/lectures'
    | '/student/materials'
    | '/student/progress'
    | '/teacher/doubts'
    | '/teacher/exams'
    | '/teacher/leaves'
    | '/teacher/question-generation'
    | '/teacher/schedule'
    | '/teacher/sessions'
    | '/teacher/students'
    | '/teacher/uploads'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/admin/access'
    | '/admin/leaves'
    | '/admin/students'
    | '/admin/teachers'
    | '/student/ai-hub'
    | '/student/ask-doubt'
    | '/student/assessments'
    | '/student/lectures'
    | '/student/materials'
    | '/student/progress'
    | '/teacher/doubts'
    | '/teacher/exams'
    | '/teacher/leaves'
    | '/teacher/question-generation'
    | '/teacher/schedule'
    | '/teacher/sessions'
    | '/teacher/students'
    | '/teacher/uploads'
    | '/admin'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/leaves'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/student/ai-hub'
    | '/_authenticated/student/ask-doubt'
    | '/_authenticated/student/assessments'
    | '/_authenticated/student/lectures'
    | '/_authenticated/student/materials'
    | '/_authenticated/student/progress'
    | '/_authenticated/teacher/doubts'
    | '/_authenticated/teacher/exams'
    | '/_authenticated/teacher/leaves'
    | '/_authenticated/teacher/question-generation'
    | '/_authenticated/teacher/schedule'
    | '/_authenticated/teacher/sessions'
    | '/_authenticated/teacher/students'
    | '/_authenticated/teacher/uploads'
    | '/_authenticated/admin/'
    | '/_authenticated/student/'
    | '/_authenticated/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/uploads': {
      id: '/_authenticated/teacher/uploads'
      path: '/teacher/uploads'
      fullPath: '/teacher/uploads'
      preLoaderRoute: typeof AuthenticatedTeacherUploadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/students': {
      id: '/_authenticated/teacher/students'
      path: '/teacher/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/sessions': {
      id: '/_authenticated/teacher/sessions'
      path: '/teacher/sessions'
      fullPath: '/teacher/sessions'
      preLoaderRoute: typeof AuthenticatedTeacherSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/schedule': {
      id: '/_authenticated/teacher/schedule'
      path: '/teacher/schedule'
      fullPath: '/teacher/schedule'
      preLoaderRoute: typeof AuthenticatedTeacherScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/question-generation': {
      id: '/_authenticated/teacher/question-generation'
      path: '/teacher/question-generation'
      fullPath: '/teacher/question-generation'
      preLoaderRoute: typeof AuthenticatedTeacherQuestionGenerationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/leaves': {
      id: '/_authenticated/teacher/leaves'
      path: '/teacher/leaves'
      fullPath: '/teacher/leaves'
      preLoaderRoute: typeof AuthenticatedTeacherLeavesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/exams': {
      id: '/_authenticated/teacher/exams'
      path: '/teacher/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof AuthenticatedTeacherExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/doubts': {
      id: '/_authenticated/teacher/doubts'
      path: '/teacher/doubts'
      fullPath: '/teacher/doubts'
      preLoaderRoute: typeof AuthenticatedTeacherDoubtsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/progress': {
      id: '/_authenticated/student/progress'
      path: '/student/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof AuthenticatedStudentProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/materials': {
      id: '/_authenticated/student/materials'
      path: '/student/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof AuthenticatedStudentMaterialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/lectures': {
      id: '/_authenticated/student/lectures'
      path: '/student/lectures'
      fullPath: '/student/lectures'
      preLoaderRoute: typeof AuthenticatedStudentLecturesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/assessments': {
      id: '/_authenticated/student/assessments'
      path: '/student/assessments'
      fullPath: '/student/assessments'
      preLoaderRoute: typeof AuthenticatedStudentAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/ask-doubt': {
      id: '/_authenticated/student/ask-doubt'
      path: '/student/ask-doubt'
      fullPath: '/student/ask-doubt'
      preLoaderRoute: typeof AuthenticatedStudentAskDoubtRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/ai-hub': {
      id: '/_authenticated/student/ai-hub'
      path: '/student/ai-hub'
      fullPath: '/student/ai-hub'
      preLoaderRoute: typeof AuthenticatedStudentAiHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/leaves': {
      id: '/_authenticated/admin/leaves'
      path: '/admin/leaves'
      fullPath: '/admin/leaves'
      preLoaderRoute: typeof AuthenticatedAdminLeavesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminLeavesRoute: typeof AuthenticatedAdminLeavesRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedStudentAiHubRoute: typeof AuthenticatedStudentAiHubRoute
  AuthenticatedStudentAskDoubtRoute: typeof AuthenticatedStudentAskDoubtRoute
  AuthenticatedStudentAssessmentsRoute: typeof AuthenticatedStudentAssessmentsRoute
  AuthenticatedStudentLecturesRoute: typeof AuthenticatedStudentLecturesRoute
  AuthenticatedStudentMaterialsRoute: typeof AuthenticatedStudentMaterialsRoute
  AuthenticatedStudentProgressRoute: typeof AuthenticatedStudentProgressRoute
  AuthenticatedTeacherDoubtsRoute: typeof AuthenticatedTeacherDoubtsRoute
  AuthenticatedTeacherExamsRoute: typeof AuthenticatedTeacherExamsRoute
  AuthenticatedTeacherLeavesRoute: typeof AuthenticatedTeacherLeavesRoute
  AuthenticatedTeacherQuestionGenerationRoute: typeof AuthenticatedTeacherQuestionGenerationRoute
  AuthenticatedTeacherScheduleRoute: typeof AuthenticatedTeacherScheduleRoute
  AuthenticatedTeacherSessionsRoute: typeof AuthenticatedTeacherSessionsRoute
  AuthenticatedTeacherStudentsRoute: typeof AuthenticatedTeacherStudentsRoute
  AuthenticatedTeacherUploadsRoute: typeof AuthenticatedTeacherUploadsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminLeavesRoute: AuthenticatedAdminLeavesRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
  AuthenticatedStudentAiHubRoute: AuthenticatedStudentAiHubRoute,
  AuthenticatedStudentAskDoubtRoute: AuthenticatedStudentAskDoubtRoute,
  AuthenticatedStudentAssessmentsRoute: AuthenticatedStudentAssessmentsRoute,
  AuthenticatedStudentLecturesRoute: AuthenticatedStudentLecturesRoute,
  AuthenticatedStudentMaterialsRoute: AuthenticatedStudentMaterialsRoute,
  AuthenticatedStudentProgressRoute: AuthenticatedStudentProgressRoute,
  AuthenticatedTeacherDoubtsRoute: AuthenticatedTeacherDoubtsRoute,
  AuthenticatedTeacherExamsRoute: AuthenticatedTeacherExamsRoute,
  AuthenticatedTeacherLeavesRoute: AuthenticatedTeacherLeavesRoute,
  AuthenticatedTeacherQuestionGenerationRoute:
    AuthenticatedTeacherQuestionGenerationRoute,
  AuthenticatedTeacherScheduleRoute: AuthenticatedTeacherScheduleRoute,
  AuthenticatedTeacherSessionsRoute: AuthenticatedTeacherSessionsRoute,
  AuthenticatedTeacherStudentsRoute: AuthenticatedTeacherStudentsRoute,
  AuthenticatedTeacherUploadsRoute: AuthenticatedTeacherUploadsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
